### ISSUE TITLE
redirects to 404 page instead of loading elementor on translation-domain

### ISSUE THREAD

**Issue by matthiaswagnerwy** [reatlat/wp-elementor-multidomain-support#2]
i'd really like to use your plugin, but on this one (live) instance i tested it, it resulted in this behaviour. is this anything you are already aware of? i will try to see if it is because of any other plugin/setting soon :)

**Comment by reatlat** [comment]
@matthiaswagnerwy not easy to debug your issue without any log :)

can you provide more information about your WP instance:
- server-side (apache, nginx, configs...)
- WP core version
- debug log
- MultiLang plugin and version

I need more information to understand where is an issue.
PS: just in case I test it in many servers and instance before publish it live and never get 404 redirect issue.

**Comment by matthiaswagnerwy** [comment]
thanks for your quick reply :) yes i know, i will try to provide more information if i can reproduce the problem in another instance. just wanted to try if maybe it was a known problem ;)
